services:
  influxdb2:
    image: influxdb:2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: raychannudam
      DOCKER_INFLUXDB_INIT_PASSWORD: Ranger@2002
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: MyInitialAdminToken0==
      DOCKER_INFLUXDB_INIT_ORG: ASEAN-MRC-TECHNOLOGY
      DOCKER_INFLUXDB_INIT_BUCKET: sensors
    volumes:
      - ./influx/data:/var/lib/influxdb2
    ports:
      - 8086:8086
    networks:
      - my_network

  # mqttservice:
  #   image: mqttservice
  #   container_name: mqttservice-container
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile.mqtt
  #   volumes:
  #     - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
  #     - ./mosquitto/data:/mosquitto/data 
  #     - ./mosquitto/log:/mosquitto/log  
  #   ports:
  #     - "1883:1883"
  #   networks:
  #    - my_network

  fastapi:
    image: fastapi-image
    container_name: fastapi
    build:
      context: ./
      dockerfile: Dockerfile.fastapi
    volumes:
      - .:/app
    expose:
      - 8000
    depends_on:
     - influxdb2
    #  - mqttservice
    networks:
      - my_network
    
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/cert/cloudflare.crt:/etc/ssl/certs/cert.crt
      - ./nginx/cert/cloudflare.key:/etc/ssl/private/cert.key
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fastapi
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
  